name: Terraform
run-name: Terraform-test

on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment
        default: dev
        required: true
jobs:
  build:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::730335519137:role/GitAction
          aws-region: us-east-1

      - name: AWS valiadtion
        run: aws sts get-caller-identity

